### ISSUE TITLE
留言板

### ISSUE THREAD

**Issue by Kira-Pgr** [Kira-Pgr/Kira-Pgr.github.io#16]
https://kira-pgr.github.io/posts/comment/ 

 For a better open source world~

**Comment by halo233** [comment]
求博主的hugo主题配置，真的好好看

**Comment by Kira-Pgr** [comment]
> @halo233
> 求博主的hugo主题配置，真的好好看

可以参考我这两篇文章qaq  
https://kira-pgr.github.io/posts/hugo1/  
https://kira-pgr.github.io/posts/hugo2/

**Comment by Kira-Pgr** [comment]
> @halo233
> 求博主的hugo主题配置，真的好好看

```yaml
baseurl: https://kira-pgr.github.io/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: KiraPGR's Blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon.png

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 
        subtitle: /* Life Runs On Code */
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: gitalk

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)
            
        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
        
        gitalk:
            owner: Kira-Pgr 
            admin: Kira-Pgr 
            repo: kira-pgr.github.io
            clientID: 你的clientID
            clientSecret: 你的clientSecret
##具体可以查查gitalk配置方法        
        cusdis:
            host: 
            id: 
    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:     
        - identifier: All Posts
          name: All Posts
          url: /posts/
          weight: 300
          params:
            icon: infinity
            newTab: false
   
        - identifier: Categories
          name: Categories
          url: /categories/
          weight: 200
          params:
            icon: link
            newTab: false
            
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Kira-Pgr
          params:
            icon: brand-github
            

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false

```
